version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./transcription.db
      - ASR_MODEL=nvidia/parakeet-tdt-0.6b-v2
      - MAX_CHUNK_DURATION=30
    # 以下はGPUが利用可能な環境で使用する場合にコメントを外してください
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]